export const PRODUCT_PAGE_LIMIT = 16;
export const PRODUCT_PAGE_NUMBER = 1;
export const CURRENCY_SYMBOL = '₺';
export const PAGINATION_SHOW_FIRST_AND_LAST_PAGES_LIMIT = 8;
export const PAGINATION_FIRST_AND_LAST_PAGES_SLICING_VALUE = 4;
